### ISSUE TITLE
Attempting to execute ASR instruction results in runtime error

### ISSUE THREAD

**Issue by Haruki-nyan** [rtybanana/irisc-web#6]
Attempting to execute an instruction like `MOV R1,R1,ASR #16` results in a error with the message "RuntimeError: While attempting to perform a flex operand optional shift."

**Comment by rtybanana** [comment]
Hi Haruki, 

Thanks for the report. I've been able to reproduce the issue and will look into it now.

**Comment by rtybanana** [comment]
I have fixed the issue and added support for ASR. GitHub appears to be having some issues with PR mergability at the moment, but I'll merge PR #7 as soon as I can.

I hope you're enjoying iRISC! :)
