### ISSUE TITLE
Support for declear arrary of data

### ISSUE THREAD

**Issue by zhenyulincs** [rtybanana/irisc-web#8]
Hi rtybanana,

The current version of compiler doesn't support declear array of data in the data section

Example:
.data
SAMPLES: .word 1, 2, -3, -4, 5, 6  //List of 32bit intergers

There will be a 
SyntaxError
Unexpected token ',' after valid data declaration end.
4 : samples: .word 1 , 2 , - 3 , - 4 , 5 , 6

I wonder do you have plan to support it in future update

Best

**Comment by rtybanana** [comment]
Hi @zhenyulincs,

Sorry for the late reply, I must've missed the email notification. I had originally intended to support this but never got round to it. I'll take a look into it, doesn't seem like it should be too hard but I've gotten busy with work recently so I can't promise that it will be sorted quickly.

In the meantime, you can get around this by declaring a uninitialised array and then initialising the values when the program starts like so:

```
.data
.balign 4

samples: .skip 24 	// initialise empty 26 byte array (6 int32s)

.text
initialise_samples:
	ldr r0, =samples
	
	mov r1, #1
	str r1, [r0], #4		// post-index updating
	
	mov r1, #2
	str r1, [r0], #4
	
	mvn r1, #3
	str r1, [r0], #4
	
	mvn r1, #4
	str r1, [r0], #4
	
	mov r1, #5
	str r1, [r0], #4
	
	mov r1, #6
	str r1, [r0], #4
	
	bx lr

main:
	push {lr, r12}
	
	bl initialise_samples
	
	pop {lr, r12}
	bx lr
```

I appreciate that that's really annoying, I'll see what I can do.

**Comment by rtybanana** [comment]
Should be working for you now. See new features in #9!
